In [101]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mlxtend.preprocessing import minmax_scaling 
import tensorflow as tf
import io
import plotly.graph_objs as go
import plotly.offline as py
import plotly.express as px

In [102]:
#upload train and test files
'''from google.colab import files
uploaded = files.upload()'''

'from google.colab import files\nuploaded = files.upload()'

In [103]:
#data loaded here
ori_data = pd.read_csv(io.BytesIO(uploaded['train.csv']))

In [104]:
display(ori_data.info(),ori_data.head())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27000 entries, 0 to 26999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          27000 non-null  int64
 1   LIMIT_BAL                   27000 non-null  int64
 2   SEX                         27000 non-null  int64
 3   EDUCATION                   27000 non-null  int64
 4   MARRIAGE                    27000 non-null  int64
 5   AGE                         27000 non-null  int64
 6   PAY_0                       27000 non-null  int64
 7   PAY_2                       27000 non-null  int64
 8   PAY_3                       27000 non-null  int64
 9   PAY_4                       27000 non-null  int64
 10  PAY_5                       27000 non-null  int64
 11  PAY_6                       27000 non-null  int64
 12  BILL_AMT1                   27000 non-null  int64
 13  BILL_AMT2                   27000 non-null  int64
 14  BILL_A

None

ID  LIMIT_BAL  SEX  ...  PAY_AMT5  PAY_AMT6  default payment next month
0  13523     160000    2  ...     14262         0                           0
1  20458     100000    1  ...       291       291                           0
2   5538     150000    1  ...      1819      4793                           0
3  29048     120000    2  ...         0       840                           0
4  10181      40000    2  ...      1400         0                           1

[5 rows x 25 columns]

In [105]:
ori_data['SEX'].unique()

array([2, 1])

In [106]:
ori_data['EDUCATION'].unique()

array([2, 1, 3, 5, 6, 4, 0])

In [107]:
ori_data.groupby(['EDUCATION']).count().max(level=0)

ID  LIMIT_BAL  ...  PAY_AMT6  default payment next month
EDUCATION                    ...                                      
0             10         10  ...        10                          10
1           9510       9510  ...      9510                        9510
2          12662      12662  ...     12662                       12662
3           4410       4410  ...      4410                        4410
4            111        111  ...       111                         111
5            250        250  ...       250                         250
6             47         47  ...        47                          47

[7 rows x 24 columns]

In [108]:
ori_data.loc[(ori_data['EDUCATION'] == 0), 'EDUCATION'] = 2

In [109]:
ori_data['EDUCATION'].unique()

array([2, 1, 3, 5, 6, 4])

In [110]:
ori_data['MARRIAGE'].unique()

array([2, 1, 3, 0])

In [111]:
ori_data.groupby(['MARRIAGE']).count().max(level=0)

ID  LIMIT_BAL  ...  PAY_AMT6  default payment next month
MARRIAGE                    ...                                      
0            44         44  ...        44                          44
1         12281      12281  ...     12281                       12281
2         14390      14390  ...     14390                       14390
3           285        285  ...       285                         285

[4 rows x 24 columns]

In [112]:
ori_data.loc[(ori_data['MARRIAGE'] == 0), 'MARRIAGE'] = 2

In [113]:
ori_data['MARRIAGE'].unique()

array([2, 1, 3])

In [114]:
absurd_age = ori_data[ori_data['AGE']>=130 ]
absurd_age.size

0

In [115]:
ori_data['PAY_0'].unique()

array([-2, -1,  0,  2,  1,  3,  4,  8,  5,  6,  7])

In [116]:
ori_data.loc[(ori_data['PAY_0'] == -2) & ((ori_data['BILL_AMT1']-ori_data['PAY_AMT1'])<=0), 'PAY_0'] = -1

In [117]:
ori_data.loc[(ori_data['PAY_0'] == -2) & (ori_data['PAY_2'] == -2) & ((ori_data['BILL_AMT2']-ori_data['PAY_AMT2'])<=0), ('PAY_0','PAY_2')] = (1,1)

In [118]:
ori_data.loc[(ori_data['PAY_0'] == -2) & (ori_data['PAY_2'] == -2) & (ori_data['PAY_3'] == -2) & ((ori_data['BILL_AMT3']-ori_data['PAY_AMT3'])<=0), ('PAY_0','PAY_2','PAY_3')] = (2,2,2)

In [119]:
ori_data.loc[(ori_data['PAY_0'] == -2) & (ori_data['PAY_2'] == -2) & (ori_data['PAY_3'] == -2) & (ori_data['PAY_4'] == -2) & ((ori_data['BILL_AMT4']-ori_data['PAY_AMT4'])<=0), ('PAY_0','PAY_2','PAY_3','PAY_4')] = (3,3,3,3)

In [120]:
ori_data.loc[(ori_data['PAY_0'] == -2) & (ori_data['PAY_2'] == -2) & (ori_data['PAY_3'] == -2) & (ori_data['PAY_4'] == -2) & (ori_data['PAY_5'] == -2) & ((ori_data['BILL_AMT5']-ori_data['PAY_AMT5'])<=0), ('PAY_0','PAY_2','PAY_3','PAY_4','PAY_5')] = (4,4,4,4,4)

In [121]:
ori_data.loc[(ori_data['PAY_0'] == -2) & (ori_data['PAY_2'] == -2) & (ori_data['PAY_3'] == -2) & (ori_data['PAY_4'] == -2) & (ori_data['PAY_5'] == -2) & (ori_data['PAY_6'] == -2) & ((ori_data['BILL_AMT6']-ori_data['PAY_AMT6'])<=0), ('PAY_0','PAY_2','PAY_3','PAY_4','PAY_5','PAY_6')] = (5,5,5,5,5,5)

In [123]:
ori_data.loc[(ori_data['PAY_0'] == -2) & (ori_data['PAY_2'] == -2) & (ori_data['PAY_3'] == -2) & (ori_data['PAY_4'] == -2) & (ori_data['PAY_5'] == -2) & (ori_data['PAY_6'] == -2) & ((ori_data['BILL_AMT6']-ori_data['PAY_AMT6'])>0), ('PAY_0','PAY_2','PAY_3','PAY_4','PAY_5','PAY_6')] = (6,6,6,6,6,6)

In [124]:
display(ori_data.isnull().sum())

ID                            0
LIMIT_BAL                     0
SEX                           0
EDUCATION                     0
MARRIAGE                      0
AGE                           0
PAY_0                         0
PAY_2                         0
PAY_3                         0
PAY_4                         0
PAY_5                         0
PAY_6                         0
BILL_AMT1                     0
BILL_AMT2                     0
BILL_AMT3                     0
BILL_AMT4                     0
BILL_AMT5                     0
BILL_AMT6                     0
PAY_AMT1                      0
PAY_AMT2                      0
PAY_AMT3                      0
PAY_AMT4                      0
PAY_AMT5                      0
PAY_AMT6                      0
default payment next month    0
dtype: int64

In [127]:
def correlation_plot():
    #correlation
    correlation = ori_data.corr()
    #tick labels
    matrix_cols = correlation.columns.tolist()
    #convert to array
    corr_array  = np.array(correlation)
    trace = go.Heatmap(z = corr_array,
                       x = matrix_cols,
                       y = matrix_cols,
                       colorscale='Viridis',
                       colorbar   = dict() 
                      )
    layout = go.Layout(dict(title = 'Correlation Matrix for variables',
                            #autosize = False,
                            #height  = 1400,
                            #width   = 1600,
                            margin  = dict(r = 0 ,l = 100,
                                           t = 0,b = 100,
                                         ),
                            yaxis   = dict(tickfont = dict(size = 9)),
                            xaxis   = dict(tickfont = dict(size = 9)),
                           )
                      )
    fig = go.Figure(data = [trace],layout = layout)
    py.iplot(fig)
correlation_plot()

In [130]:
scaled_data = minmax_scaling(ori_data,columns=['ID','LIMIT_BAL',
'SEX',
'EDUCATION',
'MARRIAGE',
'AGE',
'PAY_0',
'PAY_2',
'PAY_3',
'PAY_4',
'PAY_5',
'PAY_6',
'BILL_AMT1',
'BILL_AMT2',
'BILL_AMT3',
'BILL_AMT4',
'BILL_AMT5',
'BILL_AMT6',
'PAY_AMT1',
'PAY_AMT2',
'PAY_AMT3',
'PAY_AMT4','PAY_AMT5','PAY_AMT6'])

In [131]:
def build_model():
    model = tf.keras.Sequential([tf.keras.layers.Dense(8, activation='relu', input_shape=[len(scaled_data.keys())]),
                                tf.keras.layers.Dense(4, activation='relu'),
                                tf.keras.layers.Dense(1,activation='sigmoid')
                                ])

    optimizer = tf.keras.optimizers.RMSprop(0.01)

    model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    return model

model = build_model()

In [132]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 8)                 200       
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 36        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 5         
Total params: 241
Trainable params: 241
Non-trainable params: 0
_________________________________________________________________


In [135]:
EPOCHS = 500

history = model.fit(scaled_data, ori_data['default payment next month'],epochs=EPOCHS, validation_split=0.2, verbose=2)

Epoch 1/500
675/675 - 1s - loss: 0.4415 - accuracy: 0.8181 - val_loss: 0.4422 - val_accuracy: 0.8189
Epoch 2/500
675/675 - 1s - loss: 0.4410 - accuracy: 0.8177 - val_loss: 0.4438 - val_accuracy: 0.8180
Epoch 3/500
675/675 - 1s - loss: 0.4417 - accuracy: 0.8184 - val_loss: 0.4423 - val_accuracy: 0.8180
Epoch 4/500
675/675 - 1s - loss: 0.4402 - accuracy: 0.8172 - val_loss: 0.4486 - val_accuracy: 0.8170
Epoch 5/500
675/675 - 1s - loss: 0.4411 - accuracy: 0.8185 - val_loss: 0.4498 - val_accuracy: 0.8176
Epoch 6/500
675/675 - 1s - loss: 0.4407 - accuracy: 0.8186 - val_loss: 0.4424 - val_accuracy: 0.8183
Epoch 7/500
675/675 - 1s - loss: 0.4407 - accuracy: 0.8167 - val_loss: 0.4449 - val_accuracy: 0.8206
Epoch 8/500
675/675 - 1s - loss: 0.4413 - accuracy: 0.8187 - val_loss: 0.4499 - val_accuracy: 0.8181
Epoch 9/500
675/675 - 1s - loss: 0.4410 - accuracy: 0.8171 - val_loss: 0.4476 - val_accuracy: 0.8167
Epoch 10/500
675/675 - 1s - loss: 0.4405 - accuracy: 0.8177 - val_loss: 0.4426 - val_accura

In [137]:
test_data = pd.read_csv(io.BytesIO(uploaded['test.csv']))

In [138]:
scaled_test_data = minmax_scaling(test_data,columns=['ID','LIMIT_BAL',
'SEX',
'EDUCATION',
'MARRIAGE',
'AGE',
'PAY_0',
'PAY_2',
'PAY_3',
'PAY_4',
'PAY_5',
'PAY_6',
'BILL_AMT1',
'BILL_AMT2',
'BILL_AMT3',
'BILL_AMT4',
'BILL_AMT5',
'BILL_AMT6',
'PAY_AMT1',
'PAY_AMT2',
'PAY_AMT3',
'PAY_AMT4','PAY_AMT5','PAY_AMT6'])

In [139]:
y_hat = model.predict(scaled_test_data)
test_id = test_data['ID']

In [143]:
y_hat = [0 if i<=0.5 else 1 for i in y_hat]
temp_tuples = list(zip(test_id,y_hat))
df = pd.DataFrame(temp_tuples, columns=['ID','default payment next month'])

In [144]:
df.head()

ID  default payment next month
0  12826                           0
1   7700                           0
2   1976                           0
3  16714                           1
4   2146                           0

In [145]:
df.to_csv('output.csv')